title: <span style="color: #d36f85;">Irena Stolic</span>
logo: /assets/slikaCV.png
description: Pre-doctoral Researcher in Physics at Optics Institute "Daza de Valdés" | CSIC
#show_downloads: false
theme: jekyll-theme-minimal




